postMerge :
  preRun: 
    command:
      - npm i
      - npm run build
  
  subModules:          #Not to be changed
    
#       - name: router      
#         path : "./packages/__tests__"

#         pattern: 
#           - "./dist/esm/__tests__/setup-node.js"
#           - "./dist/esm/__tests__/router/*.spec.js"

#         framework : mocha
#         configFile : ".mocharc.json"

#       - name: router-lite 
#         path : "./packages/__tests__"

#         pattern: 
#           - "./dist/esm/__tests__/setup-node.js"
#           - "./dist/esm/__tests__/router-lite/*.spec.js"

#         framework : mocha
#         configFile : ".mocharc.json"
      
      
      - name: kernel      
        path : "./packages/__tests__"
        pattern: 
          - "./dist/esm/__tests__/setup-node.js"
          - "./dist/esm/__tests__/1-kernel/**/*.spec.js"
        
        framework : mocha
        configFile : ".mocharc.json"
      
      
#       - name: runtime      
#         path : "./packages/__tests__"
#         pattern: 
#           - "./dist/esm/__tests__/setup-node.js"
#           - "./dist/esm/__tests__/2-runtime/*.spec.js"
        
#         framework : mocha
#         configFile : ".mocharc.json"

#       - name: runtime-html      
#         path : "./packages/__tests__"
            
#         pattern: 
#           - "./dist/esm/__tests__/setup-node.js"
#           - "./dist/esm/__tests__/3-runtime-html/**/*.spec.js"
        
#         framework : mocha
#         configFile : ".mocharc.json"
        
        
#       - name: store-v1      
#         path : "./packages/__tests__"
            
#         pattern: 
#           - "./dist/esm/__tests__/setup-node.js"
#           - "./dist/esm/__tests__/store-v1/*.spec.js"
        
#         framework : mocha
#         configFile : ".mocharc.json"
        
        
        
      - name: validation      
        path : "./packages/__tests__"
            
        pattern: 
          - "./dist/esm/__tests__/setup-node.js"
          - "./dist/esm/__tests__/validation*/**/*.spec.js"
        
        framework : mocha
        configFile : ".mocharc.json"
  
preMerge : 
  
  subModules:          #Not to be changed
      - name: packages      
        path : "./packages/__tests__"
        pattern: 
          - "./dist/esm/__tests__/1-kernel/**/*.spec.js"
        
        framework : mocha
        preRun:
          command:
            - node --version
        postRun:
            command:
              - node --version
        configFile : ".mocharc.json"
        
  
version : 2.0
nodeVersion: 17.3.1

